modLoader = "javafml"
loaderVersion = "[${loaderVersion},)"
issueTrackerURL = "https://github.com/MightyPirates/Scannable/issues"
license = "MIT"

[[mods]]
modId = "scannable"
version = "${version}"
displayName = "Scannable"
displayURL = "https://github.com/MightyPirates/Scannable"
logoFile = "logo.png"
authors = "Sangar"
description = '''
Scan the area for points of interest.
'''

[[dependencies.scannable]]
modId = "forge"
mandatory = true
versionRange = "[${forgeVersion},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.scannable]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scannable]]
modId = "architectury"
mandatory = true
versionRange = "[${architecturyVersion},)"
ordering = "AFTER"
side = "BOTH"

[mc-publish]
modrinth = "YqFnwJHf"
curseforge = 266784
dependencies = [
    "architectury@>=${architecturyVersion}(required){modrinth:lhGA9TYQ}{curseforge:419699}"
]
