modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/MightyPirates/Scannable/issues"
license = "MIT"

[[mods]]
modId = "scannable"
version = "${version}"
displayName = "Scannable"
displayURL = "https://github.com/MightyPirates/Scannable"
logoFile = "logo.png"
authors = "Sangar"
description = '''
Scan the area for points of interest.
'''

[[dependencies.scannable]]
modId = "forge"
mandatory = true
versionRange = "[47.1.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.scannable]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scannable]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.scannable.mc-publish]]
modrinth = "lhGA9TYQ"
curseforge = 419699

[mc-publish]
modrinth = "YqFnwJHf"
curseforge = 266784
