[versions]
minecraft = "1.20.1"
architectury = "9.1.12"
forge = "47.1.0"

[plugins]
loom = { id = "dev.architectury.loom", version = "1.3-SNAPSHOT" }
architectury = { id = "architectury-plugin", version = "3.4-SNAPSHOT" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
spotless = { id = "com.diffplug.spotless", version = "6.20.0" }

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version = "0.14.22" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version = "0.87.0+1.20.1" }
forge = { group = "net.minecraftforge", name = "forge", version = "1.20.1-47.1.0" }
architectury-api = { group = "dev.architectury", name = "architectury", version.ref = "architectury" }
architectury-fabric = { group = "dev.architectury", name = "architectury-fabric", version.ref = "architectury" }
architectury-forge = { group = "dev.architectury", name = "architectury-forge", version.ref = "architectury" }
