modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/MightyPirates/Scannable/issues"
license = "MIT"

[[mods]]
modId = "scannable"
version = "${version}"
displayName = "Scannable"
displayURL = "https://github.com/MightyPirates/Scannable"
logoFile = "logo.png"
authors = "Sangar"
description = '''
Scan the area for points of interest.
'''

[[dependencies.scannable]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforgeVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scannable]]
modId = "minecraft"
type = "required"
versionRange = "${minecraftVersion}"
ordering = "NONE"
side = "BOTH"

[[dependencies.scannable]]
modId = "architectury"
type = "required"
versionRange = "[${architecturyVersion},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "scannable-common.mixins.json"

[[mixins]]
config = "scannable.mixins.json"

[mc-publish]
modrinth = "YqFnwJHf"
curseforge = 266784
dependencies = [
    "architectury@>=${architecturyVersion}(required){modrinth:lhGA9TYQ}{curseforge:419699}"
]
