name: publish-modrinth

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Mod Version'
        required: true
        default: '0.0.0'
      changelog:
        description: 'Changelog'
        required: true
        default: ''
      forge:
        description: 'Publish Forge Version'
        required: true
        default: true
        type: boolean
      fabric:
        description: 'Publish Fabric Version'
        required: true
        default: true
        type: boolean

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ubuntu-latest-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ubuntu-latest-gradle-
      - name: Build with Gradle
        run: ./gradlew -Psemver='${{ inputs.version }}' build

      - name: Publish to modrinth (Forge)
        if: ${{ inputs.forge }}
        run: ./gradlew -Psemver='${{ inputs.version }}' forge:modrinth
        env:
          MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
          CHANGELOG: ${{ inputs.changelog }}

      - name: Publish to modrinth (Fabric)
        if: ${{ inputs.fabric }}
        run: ./gradlew -Psemver='${{ inputs.version }}' fabric:modrinth
        env:
          MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
          CHANGELOG: ${{ inputs.changelog }}
